### ISSUE TITLE
Distance scaling or distance coloration ?

### ISSUE THREAD

**Issue by marianopeck** [paulo-raca/highcharts-draggable-3d#3]
Thank you very much for this plugin. We are gonna use it but we are lacking some features.

Do you have plans to add more controls for 3d? For example, distance-scaling (from the eye) and/or distance-coloration (or 3d lighting effects).  You know...the further the points are the smaller they look etc. 

Thanks in advance,

**Comment by paulo-raca** [comment]
Hello,
This plugin's only aim is to rotate charts when you move the mouse. I have a few features for it in my TODO list (e.g., "lock" a bunch of charts together so that they are rotated together and are always in the same orientation)

Distance-scaling points and proper lighting are reasonable features, but should be done either on Highcharts itself or on a different plugin.

Actually, I might even do it if I have the time.

What kind of chart exactly are you trying to make?

**Comment by marianopeck** [comment]
Hi @paulo-raca 

Thanks for your quick answer.  We are building a 3d scatter chart. We may need to also add bubble size for 4d as we found in this [forum](https://forum.highcharts.com/highcharts-usage/3d-chart-where-bubble-size-is-an-independent-axis-t35250/).

But the key points are...
1) the axes scale with distance (perspective) and therefore, so should the symbols/markers
2) when looking at two points, a distance-haze/coloration helps they human gage the 3d...

Of course, the rotation ... then allows the brain to interpolate and construct the 3d model in the head. Some of these charts will have a thousand points. We are presenting inputs & outputs for artificial neural networks.

See [this example](http://jsfiddle.net/oc6z1yj1/). You can see the right hand set of dots...comes at the screen, so there too... if the "closer" ones were larger, then one could identify that they arc out towards the user. 

Best,

**Comment by paulo-raca** [comment]
Your example seems like would be a nice candidate for using my [contour-curves plugin](https://www.highcharts.com/plugin-registry/single/35/contour).

It can even use the color to indicate a 4th dimension.

Otherwise, I could develop these features for you. Are you interested in a contract?

**Comment by paulo-raca** [comment]
I had some free time, and implemented the distance scaling thing:
https://github.com/highcharts/highcharts/pull/7068

**Comment by marianopeck** [comment]
Cool!!! Thank you very much. It works perfectly. Well done.
