### ISSUE TITLE
after 'mouse up', it spins a bit

### ISSUE THREAD

**Issue by lab4quant** [paulo-raca/highcharts-draggable-3d#6]
Hello, after dragging to rotate the chart, upon `mouse up` event, the chart spins a bit.
It would be great if the chart stops rotating right after `mouse up`.

**Comment by paulo-raca** [comment]
That's actually a feature :stuck_out_tongue: 
 Set snap=0 and it will be gone

**Comment by lab4quant** [comment]
@paulo-raca, great!
